### ISSUE TITLE
Implement lightGBM model

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/short-term-forecasting#10]
WHAT:
LigthGBM is a more modern version of XGBoost. Lets implement this model using the factory pattern that is allready pressent.

HOW:
- Look at how the current XGBoost model is implemented
- Implement LightGBM using the same structure
- Use the scikit learn interface (https://lightgbm.readthedocs.io/en/latest/_modules/lightgbm/sklearn.html)

TEST:
- model can be trained using lightGBM
- prediction can be made using LightGBM

**Comment by FrankKr** [comment]
Augustin and I are working on this!
