### ISSUE TITLE
Make holiday feature generation more universal

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/short-term-forecasting#12]
At present the holiday features are based on a `.csv` file (in the project) with the Dutch holidays for a couple years. This does not work well when the library is used by people/companies from other countries.

I think the most logical thing to do is moving this the the `ktpbase` package. For example by adding a `Database.get_holidays(country, date_start, date_end)` method. By doing so you can also raise an error when the right country or date range is not available.

Its also a good idea to rename the feature from the Dutch `IsFeestdag`  to something more international like `is_holiday` or `IsHoliday`.

> This is a broader discussion, but our feature names use various conventions now (CamelCase, snake_case, kerbal-case). It would be nice if we can unify this as well.

**Comment by FrankKr** [comment]
Would this be a good candidate:
https://pypi.org/project/holidays/
