### ISSUE TITLE
Use new package name (stf already taken)

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/short-term-forecasting#14]
While just testing the packaging and uploading of our package to PyPi I found out that `stf` is already used by another project:

![image](https://user-images.githubusercontent.com/6715707/108089590-12489600-707a-11eb-9e9a-c8d0b91eaaed.png)

So we need to use a different name for the package. If we want to keep it simple we could just go for:

* `st4`
* `st4casting`
* `stforecasting`
* `shortti4`
* any other variation/abbreviation of `short-term-forcasting`

But if we want we we can also think of a more unique name (perhaps better to rename the repo as well in that case).

**Comment by FrankKr** [comment]
openstf
forsea
dentia
stprog
veleda

**Comment by bremme** [comment]
Let's decide on this so we can make a first release of the package. I think I like the first two best: `openstf` or `forsea`..hmm `openstf` exists as a project on Github already (https://github.com/openstf) and forsea is the name of a company..Not sure how big of a deal that is.

**Comment by bremme** [comment]
After some discussion we are going to use `openstf`.
