### ISSUE TITLE
Fix model training unit tests

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/short-term-forecasting#3]
The train unit test don' t work anymore and are disabled at present. The main problem has to do with pickling of the model trainer. The "old"  pickled model trainer does not work anymore since various imports have changed. Making a new one does not work since we are mocking ktpbase stuff.

Ideally we want to construct a model trainer without pickle I think. Pickle makes the unit test a bit fragile like in this case. The files that need to be fixed are:

* `test/unit/model/test_train.py`
*  `test/unit/model/test_train_more.py`

**Comment by FrankKr** [comment]
Augustin and I are working on this!

**Comment by FrankKr** [comment]
fixed by https://github.com/alliander-opensource/short-term-forecasting/pull/23
