### ISSUE TITLE
[Feature] Implement fallback forecast in new pipeline

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/short-term-forecasting#70]
**WHAT:** When data completeness is low we do not want to make a regular forecast, but instead use a ‘fallback forecast’. The fallback forecast should return the daily profile of the day with the most extreme load of the past two weeks. C
Currently only a regular forecast is available in the new sklearn pipeline. Here we also implement a fallback forecast.

**HOW:**
- Look for de fallback forecast code in the old codebase 
https://github.com/alliander-opensource/short-term-forecasting/blob/2a9bf1e01f6b7554b4ba91f8fee878c1ae03b6a8/openstf/pipeline/create_forecast.py#L70
-	Implement a fallback forecast utility function that returns a forecast dataframe in case of low completeness.
-	Use above function in the predict pipeline
-	Make sure the “quality” column in de forecast dataframe has the proper value
-  Think about a logical place, should this be part of the prediction pipeline or maybe a separate pipeline?

**TEST:**
-	In case of low completeness a fallback forecast is created and written to the database in the sklearn predict pipeline
-	Information about the quality of the forecast is properly stored in de database

**Comment by FrankKr** [comment]
I've started working on the issue!

**Comment by FrankKr** [comment]
Issue fixed in PR. Closing issue
