### ISSUE TITLE
[Feature] Make a quantile model implementation that is compatible with the sklearn pipeline

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/short-term-forecasting#73]
**WHAT:** 
Currently only xgb models have been properly tested with the new pipeline. Here we implement a quantile version similar to the old pipeline.

**HOW:**
-	Decide/ check whether a multicolumn output for the predict method is compatible with sklearn.
o	If not compatible make sure the confidence interval applicator makes the proper quantile predictions
-	Make a new model based on the sklearn regressor
o	https://scikit-learn.org/stable/developers/develop.html 
-	Implement a fit method
-	Implement a predict method
-	Put the quantile model in the openstf/model folder
-	Test is new object is sklearn compatible
o	This can be easily done be running sklearn.utils.estimator_checks.check_estimator() on the new estimator

**TEST:**
-	Quantile model and forecasts are available in new pipeline.
- New Estimator object is sklearn compatible

**Comment by FrankKr** [comment]
Is this issue completed?
