### ISSUE TITLE
[Feature] Make pipelines independent of database calls

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/short-term-forecasting#74]
**WHAT:**
In the current pipeline a few database calls are made to  retriev input data and hyperparameters. It is better to give this information as input arguments to the pipeline. At the moment we have two pipelines with the new sklearn interface, apply these changes to both pipelines. Start from this branch: https://github.com/alliander-opensource/short-term-forecasting/tree/features-KTPS-1368-implement-minimal-sklearn 

**HOW:**
-	Add hyper parameters to the prediction job
-	Remove database calls from pipeline
-	Give input_data as input argument
-	Adapt pipeline functions to properly handle the new input arguments
- Input arguments of the pipeline: pd.Dataframe with input data, dict with prdeiction job and hyperparams, the two excisting booleans.
- Add the hyper parameters to the prediction job in the task.

**TEST:**
- Pipelines run independent of database calls
o E.g. this pipeline: https://github.com/alliander-opensource/short-term-forecasting/blob/2a9bf1e01f6b7554b4ba91f8fee878c1ae03b6a8/openstf/pipeline/train_model.py#L31

**Comment by bremme** [comment]
@maxi-fort Not sure if you can read the Teams messages. But its probably a better idea to discuss this issues here. I was wondering if you have been able to make some progress. Some of the things we are working on depend on this story.

Another thing I was thinking about which is maybe not totally clear in the description. Will the saving and loading of models still be part of the pipelines? I guess its more flexible to also move that out of the pipeline, but perhaps that has not been decided?

**Comment by touronaug** [comment]
Should the optimize_hyperparameters pipeline be free from db calls too? Now both the set of hyperparameters and the features set are written in the prediction job dictionary. My understanding is that the set of features is optimized like a hyperparameter. Hence should we include several sets of features in each pj? I don't understand how the hyperparameters are optimized. Do we use a grid search ? Is the hyperparams dict in the pj used in the optimization process as an initial point or is this dict only used for the final trianing once the optimization is done?

**Comment by FrankKr** [comment]
Issue fixed in PR. Closing issue
