### ISSUE TITLE
[Feature] Integrate monitoring in new pipeline

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/short-term-forecasting#89]
WHAT: In the old pipeline a report is generated about the number of succesfull jobs. This functionality is mostly implemented in the prediction job loop. However it relies on a few functions inside the pipeline. Add this funcitonality to the new pipeline. This story also includes the performance monitor.

HOW:
- Make sure implementation is modular
-  Make sure the pipeline could also be run in a notebook without the monitoring option
- Probably the prediction loop itself does not need to be modified
-  Sugestion: use callback function in the pipelines

TEST:
- (Teams) monitoring reports are available with the new pipeline
- After running a prediction job loop (train_model_task, create_forecast, optimize_hyperparameters) a report is send with information on which pj's failed and how many were succesfull.

**Comment by FrankKr** [comment]
I've started working on this issue
