### ISSUE TITLE
Apply sklearn interface on current XGBoost implementation

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/short-term-forecasting#9]
WHAT:
The sklearn interface is a more standarized way of interacting with machine learning models. In the previous story we created a model trainer for sklearn models. Use this implementation for XGBoost.

HOW:
- Use sklearn model trainer as developed in the lighGBM story
- Implement with XGBOOST

TEST:
- model can be trained using new implementation
- predecition can be made new implementation

**Comment by FrankKr** [comment]
is this covered by https://github.com/alliander-opensource/short-term-forecasting/tree/features-KTPS-1368-implement-minimal-sklearn ?

**Comment by bremme** [comment]
@FrankKr I think so. @JanMaartenvanDoorn what do you think, can be close this issue?

**Comment by bremme** [comment]
@JanMaartenvanDoorn perhaps you can answer or close this issue?

**Comment by JanMaartenvanDoorn** [comment]
Yes, I think this is already implemented
